apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bifrost-admission-controller.fullname" . }}-rolebinding
  labels:
    {{- include "bifrost-admission-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bifrost-admission-controller.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "bifrost-admission-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}